name: test-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was automatically triggered by a ${{ github.event_name }} event".
      - run: echo " This job is now running on ${{ runner.os }} server hosted by Github!!"
      - run: echo " The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo "This job status is ${{job.status}}."
